branches:
  - main

tagFormat: ${version}

plugins:
  - ['@semantic-release/commit-analyzer', { 'preset': 'conventionalcommits' }]
  - [
      '@semantic-release/release-notes-generator',
      {
        'preset': 'conventionalcommits',
        parserOpts: { 'noteKeywords': ['BREAKING CHANGE', 'BREAKING CHANGES'] },
        writerOpts: { 'commitsSort': ['subject', 'scope'] },
      },
    ]
  - [
      '@semantic-release/changelog',
      {
        'changelogFile': 'CHANGELOG.md',
        changelogTitle: '# Changelog goit-pythonweb-hw-04',
      },
    ]
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      message: 'chore(release): ${nextRelease.version} [skip ci]'
